name: build-test
on:
  pull_request:
    branches: [=projects**]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: "#nwayplay-fe-build"
        if: always()

      - uses: actions/checkout@v2

      - name: restore cache
        uses: actions/cache@v2
        id: restore-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-nwayplay-accounts-fe-dev-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        id: install-dependencies
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          touch .npmrc
          echo -e "@nwaycorp:registry=https://npm.pkg.github.com\n\n_authToken=${{ secrets.GH_TOKEN }}\nalways-auth=true" >> .npmrc
          yarn

      - name: Build
        id: build
        run: |
          yarn build:dev
        env:
          CI: false

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#nwayplay-fe-build"
          config: .github/config/slack.yml
        if: always()
